### PR TITLE
do not use docker cache when building base image

### PR DESCRIPTION
**Pull request by abbbe**
I have just encountered a problem building docker, due to something I think related to caching.
The build of base image failed during apt-get install, as it tries to use a package and gets 404-not-found.
I think it is because 'apt-get update' got cached and is not effectively executed for the base container but skipped. Probably related to "unless the RUN command _itself_ changes (and thus invalidates Docker’s on-host cache), Docker will reuse the previous results from cache" in http://thenewstack.io/understanding-the-docker-cache-for-faster-builds/.

This behavior might be specific to the revision of the docker ubuntu image I have on my PC.

$ sudo docker images ubuntu | grep 14.04
ubuntu              14.04               99ec81b80c55        6 months ago        266 MB

Anyway, this patch has solved the problem for me.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Thanks for these ideas! Could you briefly outline your use case so that I have a bit of context for these changes? I am not sure, for example, how the Ubuntu image would get created without bash installed, and why we would not simply install it if it were missing instead of changing our shell scripts back to older and more verbose conventions — but hearing more about your situation, and how you are trying to use the Playground, will probably help. Once I know your situation, I will be happy to comment on each commit with my ideas. Thanks!

**Comment by abbbe** [comment]
Please note your script uses /bin/sh, not /bin/bash, and they not 
necessarily the same.

abb@u14:~$ _lsb_release -a_
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:    trusty

abb@u14:~$ _dpkg-query -S /bin/sh_
diversion by dash from: /bin/sh
diversion by dash to: /bin/sh.distrib
dash: /bin/sh

abb@u14:~$ _dpkg-query -S /bin/bash_
bash: /bin/bash

abb@u14:~$ _ls -l /bin/sh /bin/bash_
-rwxr-xr-x 1 root root 1017016 Apr  9  2014 /bin/bash
lrwxrwxrwx 1 root root       4 Nov 15 22:37 /bin/sh -> dash

Making the script use /bin/bash instead of /bin/sh seems to be an 
equally good option, yes.

Regarding my use case, I have to admit I misuse your creation, it has 
nothing to do with learning Python. I needed a testbed to test a 
man-in-the-middle tool with clients and servers for multiple network 
protocols readily available, packaged in separate VMs or containers. 
Although the Playground is clearly not designed for, this it fits my 
needs perfectly. I break the connection between 'isp' and 'modemA' 
containers and connect each of them to another VM with a pair of GRETAP 
tunnels. That another VM runs a custom 3-leg bridge doing fully 
transparent L2/L3 mitm attack and some other funny stuff. I'll be happy 
to give you more details if it you like, otherwise will not bother you 
with more details. GRE tunnel setup scripts can be found in mitm\* 
branches in my repo.

I appreciate your offer to help very much, but can't thing of anything 
at this particular moment, the Playground does all what I need just fine.

I've figured some of the potential users might fail to troubleshoot two 
not very obvious bugs in a row (I talk about Docker cache and 
bash/non-bash issues) and will be put off. Just wanted to contribute to 
your cause ;). Please feel free to ignore my pull requests if you think 
they are irrelevant.

**Comment by brandon-rhodes** [comment]
Thank you for alerting me to the problem with the shebang lines in the shell scripts — as I am reworking the playground to work as a Vagrant image (because so many people have problems getting the VirtualBox image to launch), I have made that fix:

https://github.com/brandon-rhodes/fopnp/commit/0985009ffd4d5f4a6d101f8c747dc545f20e834d

Thanks for alerting me to it! I am planning to leave the Docker cache active, because it's a big part of what makes Docker usable — but I will see about adding a note to the documentation about it so that it hopefully does not trip anyone else up!

**Comment by brandon-rhodes** [comment]
I am going to close this pull request for now, since for my workflow the docker cache is crucially important — and is, I think, how Docker is supposed to work, preventing confusion for people who use Docker elsewhere and expect its usual caching behavior.

I might add the other scripts at some point in the future, but for the moment am going to keep things as simple as possible for the one use case that I current have the cycles to support — the use case where people bring the Playground up once, and don't stop and start it, but instead just bring down the host when they are done.

Thanks again for pointing out that my shell shebangs needed fixing!

**Comment by abbbe** [comment]
Hi Brandon,

Ok, thanks for the feedback :).

Cheers,
Alex

**Pull request closed without merging**
